### PR TITLE
Validation form

### PR DESCRIPTION
**Pull request by richie1988**
added the email validation error message and the implementation of Javascript

### CODE REVIEW

**Comment by MahmoudBakr23** [comment]
### Hi team😃, 

As much as I appreciate your hard work on this project, I'm afraid that I can't perform a review on this pull request.

**Invalid Submission**
- Please make sure that all of the team members are contributing to this PR as this is a pair-programming project. 🙏

_Your Code Review Request will be marked as invalid in your Dashboard, so please submit a new one once you are ready._ 🙏

Cheers, and Happy coding!👏👏👏

Feel free to mention @MahmoudBakr23 to leave any questions or comments in the PR thread if something is not 100% clear.

------
_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._

<hr>

_Invalid Code Review Request does not count into the code reviews limit._

**Comment by richie1988** [comment]
MY coding partner did not Show up so this is the only way to submit the
code

**Comment by richie1988** [comment]
what should i do if i cant reach out to my partner cause my partner did not
show up to work in my code

**Review by rotimiazeez — APPROVED** [review]
Hi TEAM👏🏽, 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

## Highlights
* Email validation has been added 👌🏽
* Validation works as required 👌🏽
* Good PR title and summary 👌🏽
* Descriptive README file 👌🏽

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you consider them as they can improve your code. Some of them were simply missed by the previous reviewer, and addressing them will improve your application._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Remember to tag me(@rotimiazeez) in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561), you have a limited number of reviews per project (check the exact number in your Dashboard). If you think the code review was unfair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Pull request merged**
